/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorInformationRouteImport } from './routes/visitor-information'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SevaRouteImport } from './routes/seva'
import { Route as SangeetRouteImport } from './routes/sangeet'
import { Route as LocationRouteImport } from './routes/location'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisitorInformationRoute = VisitorInformationRouteImport.update({
  id: '/visitor-information',
  path: '/visitor-information',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SevaRoute = SevaRouteImport.update({
  id: '/seva',
  path: '/seva',
  getParentRoute: () => rootRouteImport,
} as any)
const SangeetRoute = SangeetRouteImport.update({
  id: '/sangeet',
  path: '/sangeet',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sangeet': typeof SangeetRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitor-information': typeof VisitorInformationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sangeet': typeof SangeetRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitor-information': typeof VisitorInformationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/location': typeof LocationRoute
  '/sangeet': typeof SangeetRoute
  '/seva': typeof SevaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visitor-information': typeof VisitorInformationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/sangeet'
    | '/seva'
    | '/sitemap.xml'
    | '/visitor-information'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/sangeet'
    | '/seva'
    | '/sitemap.xml'
    | '/visitor-information'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/location'
    | '/sangeet'
    | '/seva'
    | '/sitemap.xml'
    | '/visitor-information'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LocationRoute: typeof LocationRoute
  SangeetRoute: typeof SangeetRoute
  SevaRoute: typeof SevaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisitorInformationRoute: typeof VisitorInformationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitor-information': {
      id: '/visitor-information'
      path: '/visitor-information'
      fullPath: '/visitor-information'
      preLoaderRoute: typeof VisitorInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seva': {
      id: '/seva'
      path: '/seva'
      fullPath: '/seva'
      preLoaderRoute: typeof SevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sangeet': {
      id: '/sangeet'
      path: '/sangeet'
      fullPath: '/sangeet'
      preLoaderRoute: typeof SangeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LocationRoute: LocationRoute,
  SangeetRoute: SangeetRoute,
  SevaRoute: SevaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisitorInformationRoute: VisitorInformationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
